_commit: v2.1.3
_src_path: gh:mopidy/cookiecutter-mopidy-ext
author_email: mail@erikbongers.net
author_full_name: Erik Bongers
dist_name: mopidy-eboplayer
ext_name: eboplayer
github_username: ErikBongers
short_description: Mopidy player based on MusicBox
