[build-system]
requires = ["setuptools >= 61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Mopidy-Eboplayer"
version = "4.0.0"
description = "First version for mopidy version 4"
readme = "README.rst"
requires-python = ">=3.11"
dependencies = [
    "Mopidy >= 4.0.0a1",
    "Pykka >= 3.1.1",
]

[project.entry-points."mopidy.ext"]
eboplayer = "mopidy_eboplayer:Extension"

[tool.setuptools.packages.find]
include = ["mopidy_eboplayer*"]