//GENERATED by build_commands.ts (although probably customized, so do a diff when regenerating).
// noinspection JSUnusedGlobalSymbols

import models, {core, Mopidy} from "../js/mopidy";
import {SearchResult} from "./refs";
import {AllUris, LibraryDict} from "./modelTypes";
import TlTrack = models.TlTrack;
import PlaybackState = core.PlaybackState;
import Playlist = models.Playlist;
import Ref = models.Ref;
import FilterCriteria = core.FilterCriteria;

type FieldName = "uri" |
"track_name" |
"album" |
"artist" |
"albumartist" |
"composer" |
"performer" |
"track_no" |
"genre" |
"date" |
"comment" |
"disc_no" |
"musicbrainz_albumid" |
"musicbrainz_artistid" |
"musicbrainz_trackid";

type Query = Object; //todo: make more specific.;

export class Commands {
    protected mopidy: Mopidy;
    core: Core;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
        this.core = new Core(mopidy);
    }
}

class Core {
    mopidy: Mopidy;
    history: Core_History;
    library: Core_Library;
    mixer: Core_Mixer;
    playback: Core_Playback;
    playlists: Core_Playlists;
    tracklist: Core_Tracklist;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
        this.history = new Core_History(mopidy);
        this.library = new Core_Library(mopidy);
        this.mixer = new Core_Mixer(mopidy);
        this.playback = new Core_Playback(mopidy);
        this.playlists = new Core_Playlists(mopidy);
        this.tracklist = new Core_Tracklist(mopidy);
    }

    //Get list of URI schemes we can handle.
    getUriSchemes(): Promise<any> {
        return this.mopidy.send("core.get_uri_schemes") as Promise<any>;
    }
    //Get version of the Mopidy core API.
    getVersion(): Promise<any> {
        return this.mopidy.send("core.get_version") as Promise<any>;
    }
}

class Core_History {
    mopidy: Mopidy;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
    }

    //Get the track history.
    //
    //Returns a list of two-tuples with timestamp and a reference to the track.
    //The timestamps are milliseconds since epoch.
    getHistory(): Promise<any> {
        return this.mopidy.send("core.history.get_history") as Promise<any>;
    }
    //Get the number of tracks in the history.
    getLength(): Promise<any> {
        return this.mopidy.send("core.history.get_length") as Promise<any>;
    }
}

class Core_Library {
    mopidy: Mopidy;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
    }

    //Browse directories and tracks at the given `uri`.
    //
    //`uri` is a string which represents some directory belonging to a
    //backend. To get the initial root directories for backends pass `None`
    //as the URI.
    //
    //Returns a list of [Ref][mopidy.models.Ref] objects for the
    //directories and tracks at the given `uri`.
    //
    //The [Ref][] objects representing tracks keep the track's original URI.
    //A matching pair of objects can look like this:
    //
    //```
    //Track(uri='dummy:/foo.mp3', name='foo', artists=..., album=...)
    //Ref.track(uri='dummy:/foo.mp3', name='foo')
    //```
    //
    //The [Ref][] objects representing directories have backend specific
    //URIs. These are opaque values, so no one but the backend that created
    //them should try and derive any meaning from them. The only valid
    //exception to this is checking the scheme, as it is used to route
    //browse requests to the correct backend.
    //
    //For example, the dummy library's `/bar` directory could be returned
    //like this:
    //
    //```
    //Ref.directory(uri='dummy:directory:/bar', name='bar')
    //```
    //
    //Args:
    //    uri: URI to browse.
    browse(uri: string | null ): Promise<any> {
        return this.mopidy.send("core.library.browse", {uri}) as Promise<any>;
    }
    //List distinct values for a given field from the library.
    //
    //This has mainly been added to support the list commands the MPD
    //protocol supports in a more sane fashion. Other frontends are not
    //recommended to use this method.
    //
    //Returns set of values corresponding to the requested field type.
    //
    //Args:
    //    field: Any one of `uri`, `track_name`, `album`, `artist`,
    //        `albumartist`, `composer`, `performer`, `track_no`, `genre`,
    //        `date`, `comment`, `disc_no`, `musicbrainz_albumid`,
    //        `musicbrainz_artistid`, or `musicbrainz_trackid`.
    //    query: Query to use for limiting results, see [search][] for
    //        details about the query format.
    getDistinct(field: FieldName, query: Query): Promise<any> {
        return this.mopidy.send("core.library.get_distinct", {field, query}) as Promise<any>;
    }
    //Lookup the images for the given URIs.
    //
    //Backends can use this to return image URIs for any URI they know about
    //be it tracks, albums, playlists. The lookup result is a dictionary
    //mapping the provided URIs to lists of images.
    //
    //Unknown URIs or URIs the corresponding backend couldn't find anything
    //for will simply return an empty list for that URI.
    //
    //Args:
    //    uris: List of URIs to find images for.
    getImages(uris: string[]): Promise<any> {
        return this.mopidy.send("core.library.get_images", {uris}) as Promise<any>;
    }
    //Lookup the given URIs.
    //
    //If the URI expands to multiple tracks, the returned list will contain
    //them all.
    //
    //Args:
    //    uris: Track URIs.
    lookup(uris: string[]): Promise<any> {
        return this.mopidy.send("core.library.lookup", {uris}) as Promise<any>;
    }
    //Refresh library. Limit to URI and below if an URI is given.
    //
    //Args:
    //    uri: Directory or track URI.
    refresh(uri: string): Promise<any> {
        return this.mopidy.send("core.library.refresh", {uri}) as Promise<any>;
    }
    //Search the library for tracks where `field` contains `values`.
    //
    //If `uris` is given, the search is limited to results from within the
    //URI roots. For example passing `uris=['file:']` will limit the search
    //to the local backend.
    //
    //Examples:
    //    ```python
    //    # Returns results matching 'a' in any backend
    //    search({'any': ['a']})
    //
    //    # Returns results matching artist 'xyz' in any backend
    //    search({'artist': ['xyz']})
    //
    //    # Returns results matching 'a' and 'b' and artist 'xyz' in any
    //    # backend
    //    search({'any': ['a', 'b'], 'artist': ['xyz']})
    //
    //    # Returns results matching 'a' if within the given URI roots
    //    # "file:///media/music" and "spotify:"
    //    search({'any': ['a']}, uris=['file:///media/music', 'spotify:'])
    //
    //    # Returns results matching artist 'xyz' and 'abc' in any backend
    //    search({'artist': ['xyz', 'abc']})
    //    ```
    //
    //Args:
    //    query: One or more queries to search for.
    //    uris: Zero or more URI roots to limit the search to.
    //    exact: If the search should use exact matching.
    search(query: Query, uris: string[], exact: boolean = false): Promise<any> {
        return this.mopidy.send("core.library.search", {query, uris, exact}) as Promise<any>;
    }
}

class Core_Mixer {
    mopidy: Mopidy;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
    }

    //Get mute state.
    //
    //`True` if muted, `False` if unmuted, `None` if unknown.
    getMute(): Promise<any> {
        return this.mopidy.send("core.mixer.get_mute") as Promise<any>;
    }
    //Get the volume.
    //
    //Integer in range [0..100] or `None` if unknown.
    //
    //The volume scale is linear.
    getVolume(): Promise<any> {
        return this.mopidy.send("core.mixer.get_volume") as Promise<any>;
    }
    //Set mute state.
    //
    //`True` to mute, `False` to unmute.
    //
    //Returns `True` if call is successful, otherwise `False`.
    setMute(mute: boolean): Promise<any> {
        return this.mopidy.send("core.mixer.set_mute", {mute}) as Promise<any>;
    }
    //Set the volume.
    //
    //The volume is defined as an integer in range [0..100].
    //
    //The volume scale is linear.
    //
    //Returns `True` if call is successful, otherwise `False`.
    setVolume(volume: number): Promise<any> {
        return this.mopidy.send("core.mixer.set_volume", {volume}) as Promise<any>;
    }
}

class Core_Playback {
    mopidy: Mopidy;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
    }

    //Get the currently playing or selected track.
    //
    //Returns a [TlTrack][mopidy.models.TlTrack] or `None`.
    getCurrentTlTrack(): Promise<any> {
        return this.mopidy.send("core.playback.get_current_tl_track") as Promise<any>;
    }
    //Get the currently playing or selected tracklist ID.
    //
    //Extracted from [get_current_tl_track][] for convenience.
    getCurrentTlid(): Promise<any> {
        return this.mopidy.send("core.playback.get_current_tlid") as Promise<any>;
    }
    //Get the currently playing or selected track.
    //
    //Extracted from [get_current_tl_track][] for convenience.
    //
    //Returns a [Track][mopidy.models.Track] or `None`.
    getCurrentTrack(): Promise<any> {
        return this.mopidy.send("core.playback.get_current_track") as Promise<any>;
    }
    //Get The playback state.
    getState(): Promise<any> {
        return this.mopidy.send("core.playback.get_state") as Promise<any>;
    }
    //Get the current stream title or `None`.
    getStreamTitle(): Promise<any> {
        return this.mopidy.send("core.playback.get_stream_title") as Promise<any>;
    }
    //Get time position in milliseconds.
    getTimePosition(): Promise<any> {
        return this.mopidy.send("core.playback.get_time_position") as Promise<any>;
    }
    //Change to the next track.
    //
    //The current playback state will be kept. If it was playing, playing
    //will continue. If it was paused, it will still be paused, etc.
    next(): Promise<any> {
        return this.mopidy.send("core.playback.next") as Promise<any>;
    }
    //Pause playback.
    pause(): Promise<any> {
        return this.mopidy.send("core.playback.pause") as Promise<any>;
    }
    //Play a track from the tracklist, specified by the tracklist ID.
    //
    //Note that the track must already be in the tracklist.
    //
    //If no tracklist ID is provided, resume playback of the currently
    //active track.
    //
    //Args:
    //    tlid: Tracklist ID of the track to play.
    play(tlid: number): Promise<any> {
        return this.mopidy.send("core.playback.play", {tlid}) as Promise<any>;
    }
    //Change to the previous track.
    //
    //The current playback state will be kept. If it was playing, playing
    //will continue. If it was paused, it will still be paused, etc.
    previous(): Promise<any> {
        return this.mopidy.send("core.playback.previous") as Promise<any>;
    }
    //If paused, resume playing the current track.
    resume(): Promise<any> {
        return this.mopidy.send("core.playback.resume") as Promise<any>;
    }
    //Seeks to time position given in milliseconds.
    //
    //Returns `True` if successful, else `False`.
    //
    //Args:
    //    time_position: Time position in milliseconds.
    seek(time_position: number): Promise<any> {
        return this.mopidy.send("core.playback.seek", {time_position}) as Promise<any>;
    }
    //Set the playback state.
    //
    ///// warning | Internal API
    //This method is only for use by Mopidy itself and extension's test suites
    //if it cannot be avoided.
    //
    //Frontends and clients must use the [`play()`][play], [`pause()`][pause],
    //[`resume()`][resume], and [`stop()`][stop] methods to change the
    //playback state.
    /////
    //
    //This method only maintains core's playback state and emits
    //`playback_state_changed` events. It has no effect on the underlying
    //backend or audio layers.
    //
    //Possible states and transitions:
    //
    //``` mermaid
    //graph LR
    //    STOPPED -->|play| PLAYING;
    //    STOPPED -->|pause| PAUSED;
    //    PLAYING -->|stop| STOPPED;
    //    PLAYING -->|pause| PAUSED;
    //    PLAYING -->|play| PLAYING;
    //    PAUSED -->|resume| PLAYING;
    //    PAUSED -->|stop| STOPPED;
    //```
    setState(new_state: PlaybackState): Promise<any> {
        return this.mopidy.send("core.playback.set_state", {new_state}) as Promise<any>;
    }
    //Stop playing.
    stop(): Promise<any> {
        return this.mopidy.send("core.playback.stop") as Promise<any>;
    }
}

class Core_Playlists {
    mopidy: Mopidy;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
    }

    //Get a list of the currently available playlists.
    //
    //Returns a list of [Ref][mopidy.models.Ref] objects referring to the
    //playlists. In other words, no information about the playlists' content
    //is given.
    asList(): Promise<any> {
        return this.mopidy.send("core.playlists.as_list") as Promise<any>;
    }
    //Create a new playlist.
    //
    //If `uri_scheme` matches an URI scheme handled by a current backend,
    //that backend is asked to create the playlist. If `uri_scheme` is
    //`None` or doesn't match a current backend, the first backend is asked
    //to create the playlist.
    //
    //All new playlists must be created by calling this method, and **not**
    //by creating new instances of [Playlist][mopidy.models.Playlist].
    //
    //Args:
    //    name: Name of the new playlist.
    //    uri_scheme: Use the backend matching the URI scheme.
    create(name: string, uri_scheme: string): Promise<Playlist> {
        return this.mopidy.send("core.playlists.create", {name, uri_scheme}) as Promise<Playlist>;
    }
    //Delete playlist identified by the URI.
    //
    //If the URI doesn't match the URI schemes handled by the current
    //backends, nothing happens.
    //
    //Returns `True` if deleted, `False` otherwise.
    //
    //Args:
    //    uri: URI of the playlist to delete.
    delete(uri: string): Promise<any> {
        return this.mopidy.send("core.playlists.delete", {uri}) as Promise<any>;
    }
    //Get the items in a playlist specified by `uri`.
    //
    //Returns a list of [Ref][mopidy.models.Ref] objects referring to the
    //playlist's items.
    //
    //If a playlist with the given `uri` doesn't exist, it returns `None`.
    getItems(uri: string): Promise<any> {
        return this.mopidy.send("core.playlists.get_items", {uri}) as Promise<any>;
    }
    //Get the list of URI schemes that support playlists.
    getUriSchemes(): Promise<any> {
        return this.mopidy.send("core.playlists.get_uri_schemes") as Promise<any>;
    }
    //Lookup playlist with given URI.
    //
    //Searches both the set of playlists and any other playlist sources.
    //Returns `None` if not found.
    //
    //Args:
    //    uri: Playlist URI.
    lookup(uri: string): Promise<any> {
        return this.mopidy.send("core.playlists.lookup", {uri}) as Promise<any>;
    }
    //Refresh the playlists.
    //
    //If `uri_scheme` is `None`, all backends are asked to refresh.
    //If `uri_scheme` is an URI scheme handled by a backend, only that
    //backend is asked to refresh. If `uri_scheme` doesn't match any
    //current backend, nothing happens.
    //
    //Args:
    //    uri_scheme: Limit to the backend matching the URI scheme.
    refresh(uri_scheme: string): Promise<any> {
        return this.mopidy.send("core.playlists.refresh", {uri_scheme}) as Promise<any>;
    }
    //Save the playlist.
    //
    //For a playlist to be saveable, it must have the `uri` attribute set.
    //You must not set the `uri` attribute yourself, but use playlist
    //objects returned by [create][] or retrieved from playlists, which will
    //always give you saveable playlists.
    //
    //The method returns the saved playlist. The return playlist may differ
    //from the saved playlist. E.g. if the playlist name was changed, the
    //returned playlist may have a different URI. The caller of this method
    //must throw away the playlist sent to this method, and use the
    //returned playlist instead.
    //
    //If the playlist's URI isn't set or doesn't match the URI scheme of a
    //current backend, nothing is done and `None` is returned.
    //
    //Args:
    //    playlist: The playlist.
    save(playlist: Playlist): Promise<any> {
        return this.mopidy.send("core.playlists.save", {playlist}) as Promise<any>;
    }
}

class Core_Tracklist {
    mopidy: Mopidy;

    constructor(mopidy: Mopidy) {
        this.mopidy = mopidy;
    }

    //Add tracks to the tracklist.
    //
    //If `uris` is given instead of `tracks`, the URIs are
    //looked up in the library and the resulting tracks are added to the
    //tracklist.
    //
    //If `at_position` is given, the tracks are inserted at the given
    //position in the tracklist. If `at_position` is not given, the tracks
    //are appended to the end of the tracklist.
    //
    //Triggers the
    //[tracklist_changed][mopidy.core.CoreListener.tracklist_changed] event.
    //
    //Args:
    //    tracks: Tracks to add.
    //    at_position: Position in tracklist to add tracks.
    //    uris: List of URIs for tracks to add.
    add(tracks: string[]): Promise<TlTrack[]> {
        return this.mopidy.send("core.tracklist.add", {tracks}) as Promise<TlTrack[]>;
    }
    //Clear the tracklist.
    //
    //Triggers the
    //[tracklist_changed][mopidy.core.CoreListener.tracklist_changed] event.
    clear(): Promise<any> {
        return this.mopidy.send("core.tracklist.clear") as Promise<any>;
    }
    //The track that will be played after the given track.
    //
    //Not necessarily the same track as [next_track][].
    //
    //Deprecated: Use [get_eot_tlid][] instead.
    //
    //Args:
    //    tl_track: The reference track.
    eotTrack(args: TODO, kwargs: TODO): Promise<any> {
        return this.mopidy.send("core.tracklist.eot_track", {args, kwargs}) as Promise<any>;
    }
    //Filter the tracklist by the given criteria.
    //
    //Each rule in the criteria consists of a model field and a list of
    //values to compare it against. If the model field matches any of the
    //values, it may be returned.
    //
    //Only tracks that match all the given criteria are returned.
    //
    //Examples:
    //    ```python
    //    # Returns tracks with TLIDs 1, 2, 3, or 4 (tracklist ID)
    //    filter({'tlid': [1, 2, 3, 4]})
    //
    //    # Returns track with URIs 'xyz' or 'abc'
    //    filter({'uri': ['xyz', 'abc']})
    //
    //    # Returns track with a matching TLIDs (1, 3 or 6) and a
    //    # matching URI ('xyz' or 'abc')
    //    filter({'tlid': [1, 3, 6], 'uri': ['xyz', 'abc']})
    //    ```
    //
    //Args:
    //    criteria: One or more rules to match by.
    filter(criteria: FilterCriteria): Promise<any> {
        return this.mopidy.send("core.tracklist.filter", {criteria}) as Promise<any>;
    }
    //Get consume mode.
    //
    //`True`
    //    Tracks are removed from the tracklist when they have been played.
    //`False`
    //    Tracks are not removed from the tracklist.
    getConsume(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_consume") as Promise<any>;
    }
    //The TLID of the track that will be played after the current track.
    //
    //Not necessarily the same TLID as returned by [get_next_tlid][].
    getEotTlid(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_eot_tlid") as Promise<any>;
    }
    //Get length of the tracklist.
    getLength(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_length") as Promise<any>;
    }
    //The TLID of the next track.
    //
    //The track that will be played if calling
    //[PlaybackController.next][mopidy.core.PlaybackController.next].
    //
    //For normal playback this is the next track in the tracklist. If repeat
    //is enabled the next track can loop around the tracklist. When random is
    //enabled this should be a random track, all tracks should be played once
    //before the tracklist repeats.
    getNextTlid(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_next_tlid") as Promise<any>;
    }
    //Returns the TLID of the previous track.
    //
    //The track that will be played if calling
    //[PlaybackController.previous][mopidy.core.PlaybackController.previous].
    //
    //For normal playback this is the previous track in the tracklist. If
    //random and/or consume is enabled it should return the current track
    //instead.
    getPreviousTlid(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_previous_tlid") as Promise<any>;
    }
    //Get random mode.
    //
    //`True`
    //    Tracks are selected at random from the tracklist.
    //`False`
    //    Tracks are played in the order of the tracklist.
    getRandom(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_random") as Promise<any>;
    }
    //Get repeat mode.
    //
    //`True`
    //    The tracklist is played repeatedly.
    //`False`
    //    The tracklist is played once.
    getRepeat(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_repeat") as Promise<any>;
    }
    //Get single mode.
    //
    //`True`
    //    Playback is stopped after current song, unless in `repeat` mode.
    //`False`
    //    Playback continues after current song.
    getSingle(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_single") as Promise<any>;
    }
    //Get tracklist as list of [TlTrack][mopidy.models.TlTrack].
    getTlTracks(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_tl_tracks") as Promise<any>;
    }
    //Get tracklist as list of [Track][mopidy.models.Track].
    getTracks(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_tracks") as Promise<any>;
    }
    //Get the tracklist version.
    //
    //Integer which is increased every time the tracklist is changed. Is not
    //reset before Mopidy is restarted.
    getVersion(): Promise<any> {
        return this.mopidy.send("core.tracklist.get_version") as Promise<any>;
    }
    //The position of the given track in the tracklist.
    //
    //If neither *tl_track* or *tlid* is given we return the index of
    //the currently playing track.
    //
    //Args:
    //    tl_track: The track to find the index of.
    //    tlid: TLID of the track to find the index of.
    index(tl_track: TODO, tlid: number): Promise<any> {
        return this.mopidy.send("core.tracklist.index", {tl_track, tlid}) as Promise<any>;
    }
    //Move the tracks in the slice `[start:end]` to `to_position`.
    //
    //Triggers the
    //[tracklist_changed][mopidy.core.CoreListener.tracklist_changed] event.
    //
    //Args:
    //    start: Position of first track to move.
    //    end: Position after last track to move.
    //    to_position: New position for the tracks.
    move(start: TODO, end: TODO, to_position: TODO): Promise<any> {
        return this.mopidy.send("core.tracklist.move", {start, end, to_position}) as Promise<any>;
    }
    //The track that will be played if calling next.
    //
    //Calls [PlaybackController.next][mopidy.core.PlaybackController.next].
    //
    //For normal playback this is the next track in the tracklist. If repeat
    //is enabled the next track can loop around the tracklist. When random is
    //enabled this should be a random track, all tracks should be played once
    //before the tracklist repeats.
    //
    //Deprecated: Use [get_next_tlid][] instead.
    //
    //Args:
    //    tl_track: The reference track.
    nextTrack(args: TODO, kwargs: TODO): Promise<any> {
        return this.mopidy.send("core.tracklist.next_track", {args, kwargs}) as Promise<any>;
    }
    //Returns the track that will be played if calling previous.
    //
    //Calls [PlaybackController.previous][mopidy.core.PlaybackController.previous].
    //
    //For normal playback this is the previous track in the tracklist. If
    //random and/or consume is enabled it should return the current track
    //instead.
    //
    //Deprecated: Use [get_previous_tlid][] instead.
    //
    //Args:
    //    tl_track: The reference track.
    previousTrack(args: TODO, kwargs: TODO): Promise<any> {
        return this.mopidy.send("core.tracklist.previous_track", {args, kwargs}) as Promise<any>;
    }
    //Remove the matching tracks from the tracklist.
    //
    //Uses [filter][] to lookup the tracks to remove.
    //
    //Triggers the
    //[tracklist_changed][mopidy.core.CoreListener.tracklist_changed] event.
    //
    //Returns the removed tracks.
    //
    //Args:
    //    criteria: One or more rules to match by.
    remove(criteria: FilterCriteria): Promise<any> {
        return this.mopidy.send("core.tracklist.remove", {criteria}) as Promise<any>;
    }
    //Set consume mode.
    //
    //`True`
    //    Tracks are removed from the tracklist when they have been played.
    //`False`
    //    Tracks are not removed from the tracklist.
    setConsume(value: boolean): Promise<any> {
        return this.mopidy.send("core.tracklist.set_consume", {value}) as Promise<any>;
    }
    //Set random mode.
    //
    //`True`
    //    Tracks are selected at random from the tracklist.
    //`False`
    //    Tracks are played in the order of the tracklist.
    setRandom(value: boolean): Promise<any> {
        return this.mopidy.send("core.tracklist.set_random", {value}) as Promise<any>;
    }
    //Set repeat mode.
    //
    //To repeat a single track, set both `repeat` and `single`.
    //
    //`True`
    //    The tracklist is played repeatedly.
    //`False`
    //    The tracklist is played once.
    setRepeat(value: boolean): Promise<any> {
        return this.mopidy.send("core.tracklist.set_repeat", {value}) as Promise<any>;
    }
    //Set single mode.
    //
    //`True`
    //    Playback is stopped after current song, unless in `repeat` mode.
    //`False`
    //    Playback continues after current song.
    setSingle(value: boolean): Promise<any> {
        return this.mopidy.send("core.tracklist.set_single", {value}) as Promise<any>;
    }
    //Shuffle the entire tracklist, or a slice.
    //
    //If `start` and `end` is given only shuffles the slice `[start:end]`.
    //
    //Triggers the
    //[tracklist_changed][mopidy.core.CoreListener.tracklist_changed] event.
    //
    //Args:
    //    start: Position of first track to shuffle.
    //    end: Position after last track to shuffle.
    shuffle(start: TODO, end: TODO): Promise<any> {
        return this.mopidy.send("core.tracklist.shuffle", {start, end}) as Promise<any>;
    }
    //Returns a slice of the tracklist.
    //
    //Limited by the given start and end positions.
    //
    //Args:
    //    start: Position of first track to include in slice.
    //    end: Position after last track to include in slice.
    slice(start: TODO, end: TODO): Promise<any> {
        return this.mopidy.send("core.tracklist.slice", {start, end}) as Promise<any>;
    }
}

