def url_to_filename(txt):
    txt = txt.replace(".", "_")
    txt = txt.replace("/", "_")
    txt = txt.replace("\\", "_")
    txt = txt.replace("-", "_")
    txt = txt.replace("~", "_")
    txt = txt.replace(":", "_")
    txt = txt.replace("/", "_")
    txt = txt.replace("?", "_")
    txt = txt.replace("#", "_")
    txt = txt.replace("[", "_")
    txt = txt.replace("]", "_")
    txt = txt.replace("@", "_")
    txt = txt.replace("!", "_")
    txt = txt.replace("$", "_")
    txt = txt.replace("&", "_")
    txt = txt.replace("(", "_")
    txt = txt.replace(")", "_")
    txt = txt.replace("*", "_")
    txt = txt.replace("+", "_")
    txt = txt.replace("'", "_")
    txt = txt.replace(";", "_")
    txt = txt.replace("%", "_")
    txt = txt.replace("=", "_")
    return txt
