import * as fs from "node:fs";

//ARGUMENTS
let inputFile = "./scripts/commands_v4.json";
let outputFileName = "./mopidy_eboplayer/www/typescript/commands.ts";
let includeComments: boolean = true;

interface Module {
    parent: Module | null,
    name: string,
    funcDefs: Set<FuncDef>,
    children: Module[]
}

interface Param {
    name: string,
    default?: string | null,
    annotations?: string | null,
}

interface FuncDef {
    module: Module;
    orgName: string;
    name: string;
    key: string;
    description: string;
    params: Param[];
    annotations: string
}

interface TypeSpec {
    typeName: string,
    typeDef?: TypeDef,
}

interface TypeDef {
    type_or_interface: "type" | "interface",
    name: string,
    def: string,
}

function getOrCreateModule(namespaces: string[], root: Module) {
    let currentModule = root;
    for (let nspace of namespaces ) {
        let foundModule = currentModule.children.find(m => m.name == nspace);
        if(foundModule) {
            //great, let's dive deeper
            currentModule = foundModule;
            continue;
        }
        //not found: create:
        let newModule: Module = {parent: currentModule, name: nspace, funcDefs: new Set(), children: []};
        currentModule.children.push(newModule);
        currentModule = newModule;
    }
    return currentModule;
}

function* treeIterator(root: Module): IterableIterator<Module> {
    yield root;
    if(root.children.length) {
        for(let child of root.children) {
            yield* treeIterator(child);
        }
    }
}

class Writer {
    prefix: string;
    buffer: string;
    types: Map<string, TypeDef>;
    constructor() {
        this.prefix = "";
        this.buffer = "";
        this.types = new Map();
    }

    write(text: string, indent?: number) {
        let indentString = indent ? ' '.repeat(indent) : '';
        this.buffer += `${indentString}${text}`;
    }

    writeLine(line: string, indent: number) {
        this.write(`${line}\n`, indent);
    }

    addType(typeDef: TypeDef) {
        this.types.set(typeDef.name, typeDef);
    }
}

main();
process.stdout.write('', () => {});

function main() {
    process.argv.forEach(function (val, index, array) {
        // console.log(index + ': ' + val);
    });

    let obj = JSON.parse(fs.readFileSync(inputFile, 'utf8'));
    let rootModule: Module = {parent: null, name: "", funcDefs: new Set(), children: []};

    let methods: any = obj;
    if (obj.result)
        methods = obj.result;

    for(let key in methods) {
        let parts = key.split(".");
        let module = getOrCreateModule(parts.slice(0, -1), rootModule);
        let funcDefJson = methods[key];
        let functionName = parts.pop() as string;
        let name = snakeToCamel(functionName);

        let funcDef: FuncDef = {
            module: module,
            orgName: functionName,
            name,
            key,
            description: funcDefJson.description,
            params: funcDefJson.params,
            annotations: funcDefJson.annotations,
        };

        module.funcDefs.add(funcDef);
    }

    let writer = new Writer();

    writer.prefix = `//GENERATED by build_commands.ts (although probably customized, so do a diff when regenerating).
// noinspection JSUnusedGlobalSymbols

import models, {core, Mopidy} from "../js/mopidy";
import {SearchResult} from "./refs";
import {AllUris, HistoryRef, LibraryDict, Uri} from "./modelTypes";
import TlTrack = models.TlTrack;
import PlaybackState = core.PlaybackState;
import Playlist = models.Playlist;
import Ref = models.Ref;
import FilterCriteria = core.FilterCriteria;
import Track = models.Track;
`;
    writer.addType({type_or_interface: "type", name: "UriScheme", def: "string"});
    writer.addType({type_or_interface: "type", name: "Percentage", def:"number"});
    writer.addType({type_or_interface: "type", name: "TracklistId", def:"number"});
    writer.addType({type_or_interface: "type", name: "DurationMs", def:"number"});
    writer.addType({type_or_interface: "type", name: "Query", def:"Object; //todo: make more specific."});
    writer.addType({type_or_interface: "type", name: "DistinctField", def:"" +
            ` "uri" |\n` +
            ` "track_name" |\n` +
            ` "album" |\n` +
            ` "artist" |\n` +
            ` "albumartist" |\n` +
            ` "composer" |\n` +
            ` "performer" |\n` +
            ` "track_no" |\n` +
            ` "genre" |\n` +
            ` "date" |\n` +
            ` "comment" |\n` +
            ` "disc_no" |\n` +
            ` "musicbrainz_albumid" |\n` +
            ` "musicbrainz_artistid" |\n` +
            ` "musicbrainz_trackid"` +
            ``});
    writer.addType({type_or_interface: "type", name: "SearchField", def: `DistinctField | "any"`});
    writer.addType({type_or_interface: "type", name: "History", def: `[number, HistoryRef][]`});

    for(let module of treeIterator(rootModule)) {
        writeModule(writer, module);
    }

    let fileWriter = fs.createWriteStream(outputFileName);
    let typesString = [...writer.types.values()]
        .map(def => `${def.type_or_interface} ${def.name} = ${def.def};`)
        .join("\n\n");
    fileWriter.write(writer.prefix);
    fileWriter.write("\n");
    fileWriter.write(typesString);
    fileWriter.write("\n");
    fileWriter.write("\n");
    fileWriter.write(writer.buffer);
    fileWriter.end();
}
// Source - https://stackoverflow.com/a/1026087
// Posted by Steve Harrison, modified by community. See post 'Timeline' for change history
// Retrieved 2026-01-07, License - CC BY-SA 4.0

function capitalizeFirstLetter(text: string) {
    return String(text).charAt(0).toUpperCase() + String(text).slice(1);
}

function getModuleClassName(childModule: Module): string {
    if(childModule.parent && childModule.parent.parent != null)
        return `${getModuleClassName(childModule.parent)}_${capitalizeFirstLetter(childModule.name)}`;
    return capitalizeFirstLetter(childModule.name);
}

function writeModule(writer: Writer, module: Module) {
    let modName = module.name;
    let exportWord = "";
    let protectedWord = "";
    if(!modName) {
        modName = "Commands";
        exportWord = "export ";
        protectedWord = "protected ";
    }
    let moduleClassName = getModuleClassName(module);
    if(!moduleClassName)
        moduleClassName = "Commands";
    writer.writeLine(`${exportWord}class ${moduleClassName} {`, 0);
    writer.writeLine(`${protectedWord}mopidy: Mopidy;`, 4);

    for(let childModule of module.children) {
        writer.writeLine(`${childModule.name}: ${getModuleClassName(childModule)};`, 4);
    }

    writer.writeLine("", 0);
    writer.writeLine(`constructor(mopidy: Mopidy) {`, 4);
    writer.writeLine(`this.mopidy = mopidy;`, 8);
    for(let childModule of module.children) {
        writer.writeLine(`this.${childModule.name} = new ${getModuleClassName(childModule)}(mopidy);`, 8);
    }
    writer.writeLine("}", 4);
    if(module.funcDefs.size)
        writer.writeLine("", 0);

    module.funcDefs.forEach(funcDef => {
        writeFunction(writer, funcDef, 4);
    });

    writer.writeLine(`}`, 0);
    writer.writeLine("", 0);
}

function writeComments(writer: Writer, funcDef: FuncDef, indent: number) {
    let dscrLines = funcDef.description.split("\n");
    dscrLines.forEach((line) => {
        writer.writeLine(`//${line}`, indent);
    });
}

function guessFunctionType(funcDef: FuncDef): Result<string, undefined> {
    let returnType = convertPythonToTypescript(funcDef.annotations);
    if (returnType == "null")
        returnType = "void";
    else if (returnType == "todo")
        returnType = "any";
    else if (returnType == "set[Any]") //todo: move this elsewhere.
        returnType = `any /*${returnType}*/`;
    return Success(`Promise<${returnType}>`);
}

function extractReturnType(funcDef: FuncDef) {
    let res = guessFunctionType(funcDef);
    if(res.success)
        return res.value;
    console.log("NEVER");
    let rxReturnType = /\s*:rtype:(.*)/gm;
    let typeLine = rxReturnType.exec(funcDef.description)?.[1] ?? "";
    if (typeLine) {
        if(typeLine.includes("{uri: list of :class:`mopidy.models.Track`}"))
            return `Promise<LibraryDict>`;
        let optional = typeLine.includes(" or :class:`None`");
        let rxListOf = /\s*list\s+of\s+(.*)/gm;
        let listOf = rxListOf.exec(typeLine)?.[1] ?? "";
        listOf = stripOrNoneAndModuleName(listOf);
        if (listOf) {
            let baseType = extractBaseType(listOf);
            if (baseType)
                return `Promise<${baseType}[]>`;
            //Ain't no list.
            console.log(`Todo: Unknown list returntype: "${listOf}"`);
        }
        typeLine = stripOrNoneAndModuleName(typeLine);
        let baseType = extractBaseType(typeLine);
        if (baseType)
            return `Promise<${baseType}>`;
        console.log(`Todo: Unknown returntype: "${typeLine}"`);
    }
    return "Promise<any>";
}

function extractBaseType(typeLine:string) {
    let rxClass = /^\s*:class:`(.*?)`/gm;
    let classType = rxClass.exec(typeLine)?.[1] ?? "";
    if (classType) {
        if(classType == "Ref")
            classType = "Ref<AllUris>";
        return convertBaseType(classType);
    }
    let rxString = /^\s*(string)(?=\s|$)/gm;
    let stringType = rxString.exec(typeLine)?.[1] ?? "";
    if (stringType) {
        return stringType;
    }
    return "";
}

function convertBaseType(baseType: string) {
    switch (baseType) {
        case "bool" : return "boolean";
        case "int" : return "number";
        case "True" : return "boolean";
        case "False" : return "boolean";
        default: return baseType;
    }
}
function writeFunction(writer: Writer, funcDef: FuncDef, indent: number) {
    if(includeComments)
        writeComments(writer, funcDef, indent);
    writer.write(`${funcDef.name}(`, indent);
    
    writeParams(writer, funcDef, indent);

    let paramsObject = "";
    if(funcDef.params.length) {
        paramsObject = `, {${funcDef.params.map(p => p.name).join(", ")}}`;
    }

    // get return type from description.
    let returnType = extractReturnType(funcDef);
    writer.writeLine(`): ${returnType} {`,0);
    writer.writeLine(`return this.mopidy.send("${funcDef.key}"${paramsObject}) as ${returnType.replaceAll(" ", "")};`, indent+4);
    writer.writeLine("}", indent);
}

function snakeToCamel(name: string) {
    return name.replace(/(_[a-z])/g, (match) =>
        match.toUpperCase().replace("_", "")
    );
}

function writeParams(writer: Writer, funcDef: FuncDef, indent: number) {
    let paramList = funcDef.params
        .map((param) => {
            let optional = "";
            let defaultValue = "";
            let type = convertPythonToTypescript(param.annotations?? "any");
            return {name: param.name, optional, type, defaultValue};
        });
    let paramString = paramList
        .map(p => {
            return `${p.name}${p.optional}: ${p.type}${p.defaultValue}`
        })
        .join(", ");
    writer.write(paramString);
}

type Result<T, E> = { success: true, value: T } | { success: false, error: E };
function Success<T>(value: T): Result<T, never> { return { success: true, value }; }
function Failure<E>(error: E): Result<never, E> { return { success: false, error }; }

function stripOrNoneAndModuleName(type: string) {
    type = type.replace(" or :class:`None`", "");
    return type.replace("mopidy.models.", "");
}

function parseGetDistinctFieldParam(descLines: string[]): TypeSpec {
    console.log(descLines)
    let argLines = descLines.slice(
        descLines.findIndex(txt => /\s*Args\s*:\s*/.test(txt)) + 1,
        descLines.findIndex(txt => /\s*query\s*:\s*/.test(txt))
        );
    let args = argLines.join(" ")
    console.log(args);
    let values = args
        .split("`")
        .slice(1)
        .map(v => v
            .replaceAll(", or", "")
            .replaceAll(",", "")
            .replaceAll(".", "")
            .trim()
        )
        .filter(value => value != "");
    console.log(values);

    return {typeName: "FieldName", typeDef: { type_or_interface: "type", name: "FieldName", def: `${values.map(v => '"' + v + '"').join(" |\n")}`}};
}

function convertPythonToTypescript(python: string) {
    return convertPythonToTypescriptPhase1(python)
        .replaceAll("text", "string")
        .replaceAll("trueFalse", "boolean");
}

function convertPythonToTypescriptPhase1(python: string) {
    python = python.replaceAll("None", "null");
    python = python
        .replaceAll("str", "text")
        .replaceAll("int",  "number")
        .replaceAll("bool",  "trueFalse")
        .replaceAll("None",  "void_or_null") //todo: NOT CORRECT!!!
        .replaceAll("dict[Uri, list[Track]]",  "LibraryDict");
    if(python.startsWith("list[")) {
        let parts = python.split(/[\[\]]/);
        let partOne = parts[1];
        if(partOne == "Ref")
            partOne = "Ref<AllUris>";
        return partOne + "[]" + parts[2];
    }
    if(python.startsWith("dict[")) {
        return `any /*${python}*/`;
    }
    if(python.startsWith("Query[")) {
        return convertPythonToTypescriptPhase1(python.replace("Query[","dict["));
    }
    if(python.startsWith("Iterable[")) {
        return convertPythonToTypescriptPhase1(python.replace("Iterable[","list["));
    }
    return python;

}
